### ISSUE TITLE
AttributeError: 'ModifiedRoberta' object has no attribute 'update_keys_to_ignore'

### ISSUE THREAD

**Issue by zoeChen119** [Yueeeeeeee/MetaEvent#1]
Traceback (most recent call last):
  File "/workspace/ZoeGPT/reference/MetaEvent/src/train_fewevent_zeroshot.py", line 299, in <module>
    train_zeroshot(args)
  File "/workspace/ZoeGPT/reference/MetaEvent/src/train_fewevent_zeroshot.py", line 105, in train_zeroshot
    model = ModifiedRoberta.from_pretrained('roberta-base', num_labels=args.N).to(args.device)
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2876, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/workspace/ZoeGPT/reference/MetaEvent/src/roberta_model.py", line 126, in __init__
    self.update_keys_to_ignore(config, ["lm_head.decoder.weight"])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModifiedRoberta' object has no attribute 'update_keys_to_ignore'

**Comment by Yueeeeeeee** [comment]
Could you check if your transformers version is the same as in requirements.txt?

**Comment by zoeChen119** [comment]
Yes, you are right, I have adjusted the version of transformers. But now it reports another error：

Namespace(seed=42, fewevent_data_dir='/workspace/ZoeGPT/reference/MetaEvent/data/fewevent', fewevent_train_file='fewshot_train.json', fewevent_dev_file='fewshot_dev.json', fewevent_test_file='fewshot_test.json', experiment_dir='experiments', output_dir='20230918033121', device='cuda', del_model=True, template='A <mask> event </s></s> {}', N=10, K=10, train_iterations=250, eval_span=25, num_task=3, max_batch=2, max_batchsize=50, max_len=64, lr_meta=1e-05, lr_decay_meta=0.1, weight_decay=0.0, lr_learner=0.001, clf_lr_multiplier=10.0, lr_of_lr=0.0001, task_updates=50, scaling_trigger=1.0, zero_shot=True, scaling_contrastive=1.0, max_grad_norm=1.0)
Some weights of ModifiedRoberta were not initialized from the model checkpoint at /workspace/ZoeGPT/MODELS/roberta-base and are newly initialized: ['classifier.bias', 'verbalizer.bias', 'verbalizer.weight', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                                                           | 0/250 [00:00<?, ?it/s]Invalid task gradients, adjust scale and zero out gradients
Invalid task gradients, adjust scale and zero out gradients
Invalid task gradients, adjust scale and zero out gradients
  0%|                                                                                                                           | 0/250 [00:24<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/ZoeGPT/reference/MetaEvent/src/train_fewevent_zeroshot.py", line 299, in <module>
    train_zeroshot(args)
  File "/workspace/ZoeGPT/reference/MetaEvent/src/train_fewevent_zeroshot.py", line 200, in train_zeroshot
    scaled_grads = torch.autograd.grad(scaler.scale(query_loss), fast_weights.values(), retain_graph=True)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 39.41 GiB total capacity; 37.28 GiB already allocated; 10.50 MiB free; 38.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Yueeeeeeee** [comment]
Hi, this is because you don't have enough GPU memory the run second-order optimization (You will need ~40GB memory for MetaAdapt). You can try out smaller models like tiny BERT or use first-order approximation to reduce memory requirements.

**Comment by zoeChen119** [comment]
I'm trying to understand the code but I'm hitting a roadblock, can you point out how to modify the code to use the first order approximation? Thanks a million.

**Comment by Yueeeeeeee** [comment]
Hi I checked the current implementation is first-order approximation, so you might want to use smaller models like tiny BERT or tiny RoBERTa

**Comment by zoeChen119** [comment]
Ok,I will try to replace RoBERTa with BERT.There is a question:Why doesn't MetaAdapt need so much memory while MetaEvent does?

**Comment by Yueeeeeeee** [comment]
This is because the output space of each training task is different, so for each training interation, we have much more training steps unitl convergence, and thus larger memory usage. You can try to reduce task_updates and discard LSLRGradientDescentLearningRule (use fixed LR instead) to reduce memory requirements:)

**Comment by zoeChen119** [comment]
I'll try them all.Thank you very much for your patience.><

**Comment by Yueeeeeeee** [comment]
Sure thing:)
