### ISSUE TITLE
can't find packages from current channels

### ISSUE THREAD

**Issue by DuTess** [Yueeeeeeee/MetaEvent#2]
when i use conda to install requirements.txt, it tell me this error:

**Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
PackagesNotFoundError: The following packages are not available from current channels:**

and there are nearly 200 packages below, so could you please tell me what channels can i use to solve this problem?
Thank you very much!

and my current channels are:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch

(It is too troublesome to search nearly 250 packages one by one from the anaconda.org, so i want to ask for some help）

**> whole error is here blow:**

Collecting package metadata (current_repodata.json): - WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1                                          done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): / WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0                                                                                                 done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - sentry-sdk==1.5.5=pypi_0
  - gitdb==4.0.9=pypi_0
  - grpcio==1.53.0=pypi_0
  - aiohttp==3.8.1=pypi_0
  - torch==1.12.1=pypi_0
  - protobuf==3.20.3=pypi_0
  - xgboost==1.7.5=pypi_0
  - typer==0.4.2=pypi_0
  - stanford-corenlp==3.9.2=pypi_0
  - seqeval==1.2.2=pypi_0
  - linear-attention-transformer==0.19.1=pypi_0
  - en-core-web-sm==3.3.0=pypi_0
  - tensorboard-data-server==0.7.0=pypi_0
  - libcublas==11.10.3.66=0
  - pyasn1-modules==0.2.8=pypi_0
  - onnxruntime==1.14.1=pypi_0
  - flask-cors==3.0.10=pypi_0
  - sentencepiece==0.1.96=pypi_0
  - xxhash==2.0.2=pypi_0
  - cuda==11.6.1=0
  - tensorflow-estimator==2.12.0=pypi_0
  - preshed==3.0.8=pypi_0
  - tensorboard==2.12.0=pypi_0
  - libcusparse==11.7.4.91=0
  - ordered-set==4.1.0=pypi_0
  - cvxpy==1.2.0=pypi_0
  - pathtools==0.1.2=pypi_0
  - markdown==3.3.6=pypi_0
  - osqp==0.6.2.post5=pypi_0
  - accelerate==0.19.0=pypi_0
  - clip==1.0=pypi_0
  - google-cloud-core==2.3.2=pypi_0
  - s3transfer==0.5.0=pypi_0
  - einops==0.6.0=pypi_0
  - spacy-legacy==3.0.10=pypi_0
  - progressbar2==4.0.0=pypi_0
  - jieba3k==0.35.1=pypi_0
  - smart-open==6.3.0=pypi_0
  - ml-dtypes==0.0.4=pypi_0
  - libcufile-dev==1.6.1.9=0
  - base58==2.1.1=pypi_0
  - wandb==0.12.10=pypi_0
  - cuda-samples==11.6.101=h8efea70_0
  - cuda-nvprune==11.6.124=he22ec0a_0
  - cuda-sanitizer-api==12.1.105=0
  - spacy-loggers==1.0.4=pypi_0
  - axial-positional-embedding==0.2.1=pypi_0
  - blis==0.7.9=pypi_0
  - cuda-runtime==11.7.1=0
  - tokenizers==0.12.1=pypi_0
  - pyserini==0.21.0=pypi_0
  - google-cloud-storage==2.7.0=pypi_0
  - bibtexparser==1.4.0=pypi_0
  - async-timeout==4.0.2=pypi_0
  - openprompt==1.0.1=pypi_0
  - pymatgen==2022.8.23=pypi_0
  - colorama==0.4.4=pypi_0
  - cuda-nvrtc-dev==11.6.124=h249d397_0
  - cached-path==1.1.6=pypi_0
  - pybtex==0.24.0=pypi_0
  - google-auth-oauthlib==0.4.6=pypi_0
  - pylatexenc==2.10=pypi_0
  - srsly==2.4.5=pypi_0
  - spacy==3.3.1=pypi_0
  - botocore==1.23.16=pypi_0
  - stanza==1.1.1=pypi_0
  - frozenlist==1.3.0=pypi_0
  - rebiber==1.1.3=pypi_0
  - vector-quantize-pytorch==1.1.5=pypi_0
  - twython==3.9.1=pypi_0
  - monty==2022.4.26=pypi_0
  - setuptools==59.5.0=pypi_0
  - sacremoses==0.0.46=pypi_0
  - multiprocess==0.70.12.2=pypi_0
  - humanfriendly==10.0=pypi_0
  - tweepy==4.8.0=pypi_0
  - jax==0.4.8=pypi_0
  - pydeck==0.7.1=pypi_0
  - pympler==1.0.1=pypi_0
  - feedparser==6.0.8=pypi_0
  - cuda-nvvp==12.1.105=0
  - cuda-compiler==11.6.2=0
  - ctranslate2==2.24.0=pypi_0
  - pytorch-pretrained-bert==0.6.2=pypi_0
  - rouge==1.0.0=pypi_0
  - simpful==2.10.0=pypi_0
  - pyfume==0.2.25=pypi_0
  - jsonnet==0.19.1=pypi_0
  - pydantic==1.8.2=pypi_0
  - colorlog==4.7.2=pypi_0
  - gds-tools==1.6.1.9=0
  - torchaudio==0.13.1=py39_cu117
  - tensorflow-hub==0.12.0=pypi_0
  - boto3==1.20.16=pypi_0
  - pycocotools==2.0.4=pypi_0
  - libcusolver==11.4.0.1=0
  - rich==12.6.0=pypi_0
  - google-crc32c==1.5.0=pypi_0
  - pybind11==2.6.1=pypi_0
  - absl-py==1.0.0=pypi_0
  - blinker==1.4=pypi_0
  - google-pasta==0.2.0=pypi_0
  - lightgbm==3.3.5=pypi_0
  - faiss-gpu==1.7.3=py3.9_h28a55e0_0_cuda11.3
  - tensorflow==2.12.0=pypi_0
  - aiosignal==1.2.0=pypi_0
  - docker-pycreds==0.4.0=pypi_0
  - shortuuid==1.0.8=pypi_0
  - requests-oauthlib==1.3.0=pypi_0
  - oauthlib==3.2.0=pypi_0
  - validators==0.18.2=pypi_0
  - simpletransformers==0.63.4=pypi_0
  - cuda-nvdisasm==12.1.105=0
  - corenlp-protobuf==3.8.0=pypi_0
  - cuda-gdb==12.1.105=0
  - libnvjpeg==11.8.0.2=0
  - cuda-cuxxfilt==11.6.124=hecbf4f6_0
  - product-key-memory==0.1.10=pypi_0
  - cuda-nvprof==12.1.105=0
  - cuda-libraries==11.7.1=0
  - yaspin==2.1.0=pypi_0
  - pdfminer-six==20220524=pypi_0
  - tsv==1.2=pypi_0
  - tinysegmenter==0.3=pypi_0
  - cachetools==4.2.4=pypi_0
  - cuda-toolkit==11.6.1=0
  - pathy==0.10.1=pypi_0
  - stanfordnlp==0.2.0=pypi_0
  - cuda-command-line-tools==11.6.2=0
  - scs==3.2.0=pypi_0
  - flatbuffers==2.0=pypi_0
  - cuda-visual-tools==11.6.1=0
  - pyjnius==1.4.2=pypi_0
  - transformers==4.19.4=pypi_0
  - cymem==2.0.7=pypi_0
  - google-resumable-media==2.4.0=pypi_0
  - libclang==16.0.0=pypi_0
  - uncertainties==3.1.7=pypi_0
  - commonmark==0.9.1=pypi_0
  - tzlocal==4.1=pypi_0
  - nmslib==2.1.1=pypi_0
  - lmdb==1.4.0=pypi_0
  - gbml==1.1.2=pypi_0
  - cuda-nsight==12.1.105=0
  - pytorch-nlp==0.5.0=pypi_0
  - tzdata==2023.3=pypi_0
  - tensorboardx==2.4.1=pypi_0
  - dill==0.3.4=pypi_0
  - catalogue==2.0.8=pypi_0
  - cuda-nvtx==11.7.91=0
  - yarl==1.7.2=pypi_0
  - argostranslate==1.7.5=pypi_0
  - huggingface-hub==0.14.1=pypi_0
  - diffusers==0.16.1=pypi_0
  - langcodes==3.3.0=pypi_0
  - smmap==5.0.0=pypi_0
  - plotly==5.10.0=pypi_0
  - gast==0.4.0=pypi_0
  - yacs==0.1.8=pypi_0
  - local-attention==1.4.3=pypi_0
  - pytorch==1.13.1=py3.9_cuda11.7_cudnn8.5.0_0
  - svgwrite==1.4.2=pypi_0
  - thinc==8.0.17=pypi_0
  - torchvision==0.14.1=py39_cu117
  - astor==0.8.1=pypi_0
  - cuda-cuobjdump==11.6.124=h2eeebcb_0
  - nsight-compute==2023.1.1.4=0
  - cython==0.29.34=pypi_0
  - python-utils==3.3.3=pypi_0
  - libcusparse-dev==11.7.2.124=hbbe9722_0
  - rsa==4.8=pypi_0
  - spglib==2.0.1=pypi_0
  - torchsummary==1.5.1=pypi_0
  - wasabi==0.10.1=pypi_0
  - kaggle==1.5.12=pypi_0
  - pillow==9.2.0=pypi_0
  - fst-pso==1.8.1=pypi_0
  - palettable==3.3.0=pypi_0
  - scipy==1.9.0=pypi_0
  - cuda-nvml-dev==11.6.55=haa9ef22_0
  - cuda-memcheck==11.8.86=0
  - ecos==2.0.10=pypi_0
  - libcufile==1.6.1.9=0
  - fairscale==0.4.6=pypi_0
  - wget==3.2=pypi_0
  - json-lines==0.5.0=pypi_0
  - keras-preprocessing==1.1.2=pypi_0
  - cuda-nvrtc==11.7.99=0
  - cuda-nvcc==11.6.124=hbba6d2d_0
  - libcufft==10.7.2.124=h4fbf590_0
  - termcolor==1.1.0=pypi_0
  - tweet-preprocessor==0.6.0=pypi_0
  - libcublas-dev==11.9.2.110=h5c901ab_0
  - stanfordcorenlp==3.9.1.1=pypi_0
  - keras==2.12.0=pypi_0
  - pytorch-cuda==11.7=h778d358_3
  - streamlit==1.5.1=pypi_0
  - cuda-nsight-compute==12.1.1=0
  - pyarrow==7.0.0=pypi_0
  - ftfy==6.1.1=pypi_0
  - datasets==1.18.3=pypi_0
  - linformer==0.2.1=pypi_0
  - sgmllib3k==1.0.0=pypi_0
  - cuda-cudart==11.7.99=0
  - google-auth==2.15.0=pypi_0
  - cuda-tools==11.6.1=0
  - libcurand-dev==10.3.2.106=0
  - argparse==1.4.0=pypi_0
  - googleapis-common-protos==1.57.0=pypi_0
  - pandas==2.0.1=pypi_0
  - tensorlayer==2.2.5=pypi_0
  - higher==0.2.1=pypi_0
  - pytz-deprecation-shim==0.1.0.post0=pypi_0
  - fuzzytm==2.0.5=pypi_0
  - opt-einsum==3.3.0=pypi_0
  - newspaper3k==0.2.8=pypi_0
  - qdldl==0.1.5.post2=pypi_0
  - hypopt==1.0.9=pypi_0
  - libfaiss==1.7.3=hfc2d529_0_cuda11.3
  - gitpython==3.1.26=pypi_0
  - astunparse==1.6.3=pypi_0
  - latexcodec==2.0.1=pypi_0
  - libnpp==11.7.4.75=0
  - opencv-python==4.5.5.64=pypi_0
  - emoji==1.7.0=pypi_0
  - tensorboard-plugin-wit==1.8.0=pypi_0
  - multidict==6.0.2=pypi_0
  - google-api-core==2.11.0=pypi_0
  - murmurhash==1.0.9=pypi_0
  - coloredlogs==15.0.1=pypi_0
  - rdkit==2022.9.5=pypi_0
  - altair==4.2.0=pypi_0
  - libnpp-dev==11.6.3.124=h3c42840_0
  - promise==2.3=pypi_0
  - feedfinder2==0.0.4=pypi_0
  - wand==0.6.10=pypi_0
  - miniful==0.0.6=pypi_0
  - libcurand==10.3.2.106=0
  - cryptography==38.0.1=pypi_0
  - tensorflow-io-gcs-filesystem==0.32.0=pypi_0
  - cssselect==1.1.0=pypi_0
  - overrides==7.3.1=pypi_0
  - pdfplumber==0.7.5=pypi_0
  - cuda-cupti==11.7.101=0
  - svgling==0.3.1=pypi_0
  - libnvjpeg-dev==11.6.2.124=hb5906b9_0

Current channels:

  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page

**Comment by hodorxxx** [comment]
the same problem too, have you solved yet?

**Comment by DuTess** [comment]
> the same problem too, have you solved yet?

not yet，，，(TдT)

**Comment by Yueeeeeeee** [comment]
You can start with important packages like pytorch, transformers and try to run the commands. Not all packages are necessary, it's just my working environment.

**Comment by DuTess** [comment]
> You can start with important packages like pytorch, transformers and try to run the commands. Not all packages are necessary, it's just my working environment.

thank you very much! i'll try it later!
