### ISSUE TITLE
i want to train this model without prompt template, but it didn't work

### ISSUE THREAD

**Issue by DuTess** [Yueeeeeeee/MetaEvent#6]
i set "prompt_template = None" in train_fewevent_fewshot.py ----> def train_fewshot(args) ---->   train_loader, val_loader, test_loader, vocab = data_loaders(args, args.N, args.K, args.max_len,  tokenizer, prompt_template=args.template, train_size=args.num_task)

and also tried set "-template', default=' '" in main ----->    parser.add_argument('--template', default='A <mask> event </s></s> {}', type=str, help='prompt template for inference')

but it didn't work

**error is here:**
Traceback (most recent call last):
  File "/src/train_fewshot.py", line 343, in <module>
    train_fewshot(args)
  File "/src/train_fewshot.py", line 199, in train_fewshot
    outputs = functional_modifiedroberta(fast_weights, model.config,
  File "/src/roberta_functional.py", line 16, in functional_modifiedroberta
    outputs = functional_roberta(fast_weights, config, input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids,
  File "/src/roberta_functional.py", line 110, in functional_roberta
    input_shape = input_ids.size()
AttributeError: 'list' object has no attribute 'size'

could you please tell me how to train this model without prompt template? thank you very much!!!! and bless you have a good day~

**Comment by Yueeeeeeee** [comment]
Hi, you can try to use prompt like '\<mask\>: {}' as we use \<mask\> for prediction and the format function to fill in the tokens. Please also make sure the input_ids are pytorch tensors:)
